            - name: Monorepo Split
  # You may pin to the exact commit or the version.
  # uses: danharrin/monorepo-split-github-action@ac9845270ef47266435b4f124b133a323619e738
  uses: danharrin/monorepo-split-github-action@v2.3.0
  with:
    # Local package directory
    package_directory: './'
    # Host
    repository_host: # optional, default is github.com
    # Remote organization
    repository_organization: 'codesphere-community'
    # Remote repository
    repository_name: 'templates'
    # Git branch
    branch: # default is main
    # [Optional] Tag to be released
    tag: # optional
    # Git User Email
    user_email: 'jan-david.wiederstein@codesphere.com'
    # Git User Name
    user_name: 'Datata1'
          
