name: Sync Monorepo with Individual Repos

on:
  push:
    branches:
      - main  # Anpassen, falls Ihre Hauptbranch einen anderen Namen hat

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Directories
        run: |
          # Liste alle Ordner im Monorepo auf
          dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
          echo "$dirs" > directories.txt

      - name: Sync Repositories
        run: |
          # Schleife über alle Ordner im Monorepo
          while IFS= read -r dir; do
            # Extrahiere Ordnernamen
            dir=${dir#*/}
            # Überprüfe, ob das Repository bereits existiert
            if [ ! -d "$dir/.git" ]; then
              # Erstelle ein neues Repository in der Organisation
              curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" -d '{"name": "'"$dir"'"}' https://api.github.com/orgs/codesphere-community/repos
              cd $dir
              git init
              git add .
              git commit -m "Initial commit"
              git remote add origin git@github.com:your-organization/$dir.git
              git push -u origin main
              cd ..
            else
              # Aktualisiere das bestehende Repository
              cd $dir
              git add .
              git commit -m "Update from monorepo"
              git push origin main
              cd ..
            fi
          done < directories.txt
