name: Split Subfolders

on:
  push:
    branches:
      - main

jobs:
  split-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installiere jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Anzeigen von jq-Version
        run: jq --version

      - name: Download git-filter-repo
        run: |
          curl -O https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          chmod +x git-filter-repo
          sudo mv git-filter-repo /usr/local/bin/ # Move git-filter-repo to a directory in the $PATH
          
      - name: Set up Git
        run: |
          NAME='Datata1'
          MAIL='jdwiederstein01@gmail.com'
          git config --global user.email $MAIL
          git config --global user.name $NAME
      
      - name: List subfolders
        run: |
          find . -mindepth 1 -maxdepth 1 -type d \( ! -name '.github' -a ! -name '.git' \) -exec basename {} \; > subfolders.txt
          cat subfolders.txt
      
      - name: Process subfolders
        run: |
          while IFS= read -r subfolder; do
            # Clone the templates repository
            git clone https://github.com/codesphere-community/templates
            
            # Navigate to the subfolder
            cd templates/$subfolder

            # Apply git-filter-repo
            git-filter-repo --subdirectory-filter "$subfolder"
            
            ## Check if repository already exists
            REMOTE_URL="github.com/codesphere-community/${subfolder}.git"
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -L "$REMOTE_URL")
            
            if [ $RESPONSE -eq 404 ]; then
              # Repository does not exist, create it using GitHub CLI
              gh repo create codesphere-community/${subfolder} --public
            fi
            
            # Initialize new repository
            git remote add origin https://Datata1:${{ secrets.ACCESS_TOKEN }}@$REMOTE_URL
            
            # Push changes
            git push -u origin main

            # Remove self as contributor
            gh api -X DELETE "/repos/codesphere-community/$subfolder/collaborators/${{ github.actor }}"

            # Anzeigen der Beitragenden für einen bestimmten Ordner und Schreiben in eine Datei
            git shortlog -sne > contributors.txt
            cat contributors.txt
           
            while IFS= read -r contributor; do
              echo "Adding $contributor as collaborator..."
              gh api -X PUT "/repos/codesphere-community/$subfolder/collaborators/$contributor"
            done < contributors.txt

            # Clean up repository
            cd ../..
            rm -rf templates

          done < subfolders.txt

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
