name: Monorepo Split
on:
  push:
    branches:
      - main  # oder den Namen deiner Hauptbranch

jobs:
  monorepo-split:
    name: Monorepo Split Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Monorepo Split Action
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: './'
          repository_host: github.com
          repository_organization: 'codesphere-community'
          repository_name: 'templates'
          branch: 'main'
          user_email: 'jan-david.wiederstein@codesphere.com'
          user_name: 'Datata1'
