name: Split Subfolders and Push

on:
  push:
    branches:
      - main

jobs:
  split-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download git-filter-repo
        run: |
          curl -O https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          chmod +x git-filter-repo
          
      - name: test
        run: |
          ls 
          pwd

      - name: Set up Git
        run: |
          git config --global user.email "jan-david.wiederstein@codesphere.com"
          git config --global user.name "Datata1"
      
      - name: List subfolders
        run: |
          find . -mindepth 1 -maxdepth 1 -type d -exec basename {} \; > subfolders.txt
      
      - name: Process subfolders
        run: |
          while IFS= read -r subfolder; do
            # Clone the templates repository
            git clone https://github.com/codesphere-community/templates
            
            # Navigate to the subfolder
            cd templates
            
            # Apply git-filter-repo
            ./templates/git-filter-repo --subdirectory-filter "$subfolder"
            
            # Check if repository already exists
            REMOTE_URL="https://github.com/codesphere-community/${subfolder}.git"
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$REMOTE_URL")
            
            if [ $RESPONSE -eq 404 ]; then
              # Repository does not exist, create it
              curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"name\":\"${subfolder}\",\"private\":false}" "https://api.github.com/user/repos"
            fi
            
            # Initialize new repository
            git remote add origin "$REMOTE_URL"
            
            # Push changes
            git add .
            git commit -m "Extracted $subfolder"
            git push -u origin main
            
            # Clean up repository
            cd ..
            
          done < subfolders.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
