name: Split Subfolders and Push

on:
  push:
    branches:
      - main

jobs:
  split-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download git-filter-repo
        run: |
          curl -O https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo
          chmod +x git-filter-repo

      - name: Set up Git
        run: |
          git config --global user.email "jan-david.wiederstein@codesphere.com"
          git config --global user.name "Datata1"
      
      - name: List subfolders
        run: |
          find . -mindepth 1 -maxdepth 1 -type d -exec basename {} \; > subfolders.txt
      
      - name: Process subfolders
        run: |
          while IFS= read -r subfolder; do
            REMOTE_URL="https://github.com/codesphere-community/${subfolder}.git"
            ./git-filter-repo --subdirectory-filter "$subfolder"
            git init
            git remote add origin "$REMOTE_URL"
            git add .
            git commit -m "Extracted $subfolder"
            git push -u origin main
          done < subfolders.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

